---
title: "BDA_503_BKM"
author: "Özgün Kurt"
date: "11/12/2019"
output:
  pdf_document: default
  html_document: default
---


```{r}
#REQUIRED LIBRARIES
library(tidyverse)
library(dplyr)
library(ggplot2 )
library(rvest)
library(stringr)
library(scales)
library(plyr)
library(reshape2)
```

```{r}
## IMPORT DATA
#TO GET LIST OF URL OF BKM  

x <- list()
for (i in 0:9){
  for (k in 1:12) {
x[[paste0("url201",i,"0",k)]]<-paste0("https://bkm.com.tr/secilen-aya-ait-sektorel-gelisim/?filter_year=201",i,"&filter_month=",k,"&List=Listele")
  }
}
```


```{r}
#GETTING DATA FROM URL LIST AND BINDING TO ALL INVOLVED ONE DATAFRAME
DF<-data.frame(matrix(ncol = 5, nrow = 0))

for (i in x){
 HTML_1<-read_html(i) 
 temp_DF<-html_table(html_nodes(HTML_1, "table"),fill = TRUE)[[4]]
 
 for (n in 1:nrow(temp_DF)){
   temp_DF$date[[n]]<-str_remove_all(gsub(".*year=(.+)&filter_month=", "\\1", i),"[A-Z]|[a-z]|&|=")
 }
 DF<-bind_rows(DF,temp_DF)
}
DF
```

```{r}
#DATA WRANGLING & CONTROL OF FINAL FORM OF DATA
DF$year = substr(DF$date, 1,4)
DF$month = substr(DF$date,start=5,stop=6)
colnames(DF)<-c("Sector","Trans_Numb_CC","Trans_Numb_DC","Trans_Amount_CC","Trans_Amount_DC","date","year","month")
DF<-DF%>%filter(Sector!="İşyeri Grubu")%>%filter(Sector!="TOPLAM")%>%filter(Sector!="Lütfen listeyi görebilmek için yukarıdan tarih seçiniz.")
str(DF)
DF$Trans_Numb_CC<-gsub("[.]", "",DF$Trans_Numb_CC)
DF$Trans_Numb_DC<-gsub("[.]", "",DF$Trans_Numb_DC)
DF$Trans_Amount_CC<-gsub("[.]", "",DF$Trans_Amount_CC)
DF$Trans_Amount_DC<-gsub("[.]", "",DF$Trans_Amount_DC)
DF$Trans_Amount_CC<-gsub("[,]", ".",DF$Trans_Amount_CC)
DF$Trans_Amount_DC<-gsub("[,]", ".",DF$Trans_Amount_DC)

DF$Trans_Numb_CC<- as.numeric(as.character(DF$Trans_Numb_CC))
DF$Trans_Numb_DC<- as.numeric(as.character(DF$Trans_Numb_DC))
DF$Trans_Amount_CC<- as.numeric(as.character(DF$Trans_Amount_CC))
DF$Trans_Amount_DC<- as.numeric(as.character(DF$Trans_Amount_DC))

str(DF)

```










```{r}
#Differences between credit_c and debit_c transaction
trans_num <- DF %>% group_by(year) %>% 
  summarise(number_cc=sum(Trans_Numb_CC), number_dc= sum(Trans_Numb_DC)) %>%
  mutate(diff_in_numb=(number_cc-number_dc))# slice(1:9)
trans_num
```

```{r}
ggplot(trans_num, aes(x = year, y= diff_in_numb,group=1)) + 
    geom_smooth(color="blue")+
  geom_point(color="red")+
  labs(title = "Differences between credit_c and debit_c transaction", 
       subtitle = "Katilimci Sayisi", 
       caption="(based on data from EGM)")+
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle= 35, vjust= 0.5))
```




```{r}
# Transaction Amount Comparision of top 5 sector between 2010-2019

sector_share <- DF %>% group_by(Sector) %>% 
  summarise(total_amount=sum(Trans_Amount_CC + Trans_Amount_DC)) %>%
  arrange(desc(total_amount)) %>%
  mutate(share_percentage = round(total_amount / sum(total_amount)*100,2)) %>%
  slice(1:5)
sector_share
```

```{r}
#Market share based on the top 5 sectors
ggplot(sector_share, aes(x=Sector,y=share_percentage, fill=Sector)) +
geom_bar(stat = "identity") +
coord_polar() +
geom_text(
  aes(x=, y= share_percentage, label= percent(share_percentage/100)), 
  position = position_stack(vjust = 1,8),
  size=4,angle=0)
  
```

```{r}
##Credit Card and Debit Card Transaction Amount for Market BETWEEN 2010-2018
total <- DF %>% group_by(year) %>% 
  summarise(total_cc = sum(Trans_Amount_CC), total_dc = sum(Trans_Amount_DC)) %>% 
  mutate(total_amount = (total_cc + total_dc)) %>% 
  filter( year %in% c(2010:2018)) %>%
  arrange(year)
total
```



