---
title: "R_Markdown_Homework"
output: html_document
---

#### Ozgun Kurt
##### _September 30, 2019_

### About Me

In my undergraduate years at faculty of economics, I had additionally acquired an advanced knowledge about mathematical theories and statistical methods and have enhanced my understanding of implementation of those theories and methods during my previous work experiences as a data analyst. At those times, my main goal was to properly find conclusion by working with figures, facts and numbers on special computerize software. While being excited by what I was dealing with, I have realized that my current knowledge was insufficient to let me handle with the hard problems in world of data and fulfill my ideal.

So that, my expectation with this course is gaining skills in the fields of Big Data and I hope, with this program, I will be able to assist making business decisions by using the power of big data and technology.

[linkedin](https://www.linkedin.com/in/mehmet-ozgun-kurt-bb0a867a/)

***

### useR! 2019 videos

[Lightning Talk 7 - Methods & applications
](https://www.youtube.com/watch?v=uhQMBArGXRE&t=433s)

With this video, participants shows different methods and applications. Magen Beckett from Cape Town South America mentions about spatial optimisation with OSRM and R. This package allows to compute distances between points and travel time matrices.With this way you can find the perfect running route.The other participant is Angeline Protacio.Her project is using R and the Tidyverse to assist decision-making on drafts in fantasy baseball.

***

### Other R-related videos which I am interested

[Introduction to Using R for Sport Science Data Analysis](https://www.youtube.com/watch?v=eQ48QEAwgjI&t=205s)

Neil Collins working as an applied sport scientist/S&C coach, mainly in team sports.He started using data analysis techniques more frequently to help with my work (GPS/HR analysis, force/time data, load monitoring etc.). He mentions that R offers the ability to automate analysis while also offering considerably quick analysis.

The first part of video series shows some basic ways to look at and dig into your data through R and RStudio with a sample dataset with a seasons worth of GPS data.

[Basketball Analytics: Using Player Tracking Data and R](https://www.youtube.com/watch?v=4kqTBO5KDr4)

Alexander D’Amour’s talk on how to use player tracking data and R to do basketball analytics

***

### R related articles

[6 Reasons To Learn R For Business](https://www.business-science.io/business/2017/12/27/six-reasons-to-use-R-for-business.html)

This article shows benefits of learning and applying “R” for business people.


